-- 从 Open Trivia Database 获取的计算机科学题目
-- 生成时间: 2026-05-16 01:39:13
-- 分类ID: 18 (计算机科学)

INSERT INTO questions (type, difficulty, content, options, answer, explanation, score, bank_id, create_time, update_time) VALUES
  ('single', 'medium', 'In programming, the ternary operator is mostly defined with what symbol(s)?', '["?", "?:", "if then", "??"]', '?:', '分类: Science: Computers', 20, 1, NOW(), NOW()),
  ('single', 'easy', 'When Gmail first launched, how much storage did it provide for your email?', '["Unlimited", "1GB", "512MB", "5GB"]', '1GB', '分类: Science: Computers', 10, 1, NOW(), NOW()),
  ('judge', 'easy', 'In most programming languages, the operator ++ is equivalent to the statement "+= 1".', '["对", "错"]', '对', '分类: Science: Computers', 10, 1, NOW(), NOW()),
  ('judge', 'medium', 'The ''Raspberry Pi'' series of single-board computers were created in the United States.', '["对", "错"]', '错', '分类: Science: Computers', 20, 1, NOW(), NOW()),
  ('single', 'medium', 'What is the main CPU is the Sega Mega Drive / Sega Genesis?', '["Yamaha YM2612", "Zilog Z80", "Motorola 68000", "Intel 8088"]', 'Motorola 68000', '分类: Science: Computers', 20, 1, NOW(), NOW()),
  ('single', 'hard', 'Which data structure does FILO apply to?', '["Stack", "Tree", "Queue", "Heap"]', 'Stack', '分类: Science: Computers', 30, 1, NOW(), NOW()),
  ('single', 'hard', 'Who is the founder of Palantir?', '["Peter Thiel", "Jack Dorsey", "Marc Benioff", "Mark Zuckerberg"]', 'Peter Thiel', '分类: Science: Computers', 30, 1, NOW(), NOW()),
  ('single', 'medium', 'Which internet company began life as an online bookstore called ''Cadabra''?', '["Amazon", "Overstock", "Shopify", "eBay"]', 'Amazon', '分类: Science: Computers', 20, 1, NOW(), NOW()),
  ('judge', 'medium', 'AMD created the first consumer 64-bit processor.', '["对", "错"]', '对', '分类: Science: Computers', 20, 1, NOW(), NOW()),
  ('single', 'easy', 'In networking, what does OSPF stand for?', '["Open Signal Path Finder", "Open Shortest Path First", "Order State Part First", "Order Sense Ping Find"]', 'Open Shortest Path First', '分类: Science: Computers', 10, 1, NOW(), NOW()),
  ('single', 'medium', 'In HTML, which non-standard tag used to be be used to make elements scroll across the viewport?', '["<marquee></marquee>", "<scroll></scroll>", "<slide></slide>", "<move></move>"]', '<marquee></marquee>', '分类: Science: Computers', 20, 1, NOW(), NOW()),
  ('judge', 'hard', 'DHCP stands for Dynamic Host Configuration Port.', '["对", "错"]', '错', '分类: Science: Computers', 30, 1, NOW(), NOW()),
  ('single', 'medium', 'Which one of these is not an official development name for a Ubuntu release?', '["Wily Werewolf", "Utopic Unicorn", "Mystic Mansion", "Trusty Tahr"]', 'Mystic Mansion', '分类: Science: Computers', 20, 1, NOW(), NOW()),
  ('single', 'medium', 'The teapot often seen in many 3D modeling applications is called what?', '["3D Teapot", "Pixar Teapot", "Tennessee Teapot", "Utah Teapot"]', 'Utah Teapot', '分类: Science: Computers', 20, 1, NOW(), NOW()),
  ('single', 'hard', 'CMOS is tech used for constructing integrated circuits. What does CMOS stand for?', '["Complementary metal–oxide–semiconductor", "Computer-made oscillating static", "Complementary magnetic-ohms-semiconductor", "Computer-made operating system"]', 'Complementary metal–oxide–semiconductor', '分类: Science: Computers', 30, 1, NOW(), NOW()),
  ('single', 'medium', 'Which programming language was developed by Sun Microsystems in 1995?', '["Solaris OS", "C++", "Java", "Python"]', 'Java', '分类: Science: Computers', 20, 1, NOW(), NOW()),
  ('judge', 'easy', 'Linus Torvalds created Linux and Git.', '["对", "错"]', '对', '分类: Science: Computers', 10, 1, NOW(), NOW()),
  ('judge', 'easy', 'The name of the programming language AWK is abbreviated from the names of the developers – Aho, Weinberger, and Kernighan.', '["对", "错"]', '对', '分类: Science: Computers', 10, 1, NOW(), NOW()),
  ('single', 'medium', 'Which of the following is a personal computer made by the Japanese company Fujitsu?', '["MSX", "Xmillennium ", "PC-9801", "FM-7"]', 'FM-7', '分类: Science: Computers', 20, 1, NOW(), NOW()),
  ('single', 'easy', 'What does SSD stand for?', '["Solution Source Disk", "Source Solution Drive", "Solid State Disk", "Solid State Drive"]', 'Solid State Drive', '分类: Science: Computers', 10, 1, NOW(), NOW()),
  ('judge', 'medium', 'The common software-programming acronym "I18N" comes from the term "Interlocalization".', '["对", "错"]', '错', '分类: Science: Computers', 20, 1, NOW(), NOW()),
  ('single', 'medium', 'What did the name of the Tor Anonymity Network orignially stand for?', '["The Only Router", "The Ominous Router", "The Onion Router", "The Orange Router"]', 'The Onion Router', '分类: Science: Computers', 20, 1, NOW(), NOW()),
  ('single', 'hard', 'Which RAID array type is associated with data mirroring?', '["RAID 5", "RAID 0", "RAID 1", "RAID 10"]', 'RAID 1', '分类: Science: Computers', 30, 1, NOW(), NOW()),
  ('single', 'medium', 'What was the first Android version specifically optimized for tablets?', '["Eclair", "Froyo", "Honeycomb", "Marshmellow"]', 'Honeycomb', '分类: Science: Computers', 20, 1, NOW(), NOW()),
  ('judge', 'easy', 'The programming language "Python" is based off a modified version of "JavaScript".', '["对", "错"]', '错', '分类: Science: Computers', 10, 1, NOW(), NOW()),
  ('single', 'easy', 'What amount of bits commonly equals one byte?', '["64", "8", "1", "2"]', '8', '分类: Science: Computers', 10, 1, NOW(), NOW()),
  ('single', 'medium', 'How many bits make up the significand portion of a single precision floating point number?', '["8", "15", "53", "23"]', '23', '分类: Science: Computers', 20, 1, NOW(), NOW()),
  ('single', 'hard', 'Released in 2001, the first edition of Apple''s Mac OS X operating system (version 10.0) was given what animal code name?', '["Puma", "Cheetah", "Tiger", "Leopard"]', 'Cheetah', '分类: Science: Computers', 30, 1, NOW(), NOW()),
  ('judge', 'medium', 'The open source program Redis is a relational database server.', '["对", "错"]', '错', '分类: Science: Computers', 20, 1, NOW(), NOW()),
  ('single', 'hard', 'What is the name of the process that sends one qubit of information using two bits of classical information?', '["Quantum Entanglement", "Quantum Teleportation", "Super Dense Coding", "Quantum Programming"]', 'Quantum Teleportation', '分类: Science: Computers', 30, 1, NOW(), NOW()),
  ('single', 'medium', 'Originally used in PCM adapters, what frequency is the standard for sampling audio in the Compact Disc Digital Audio format?', '["32.0 kHz", "20.5 kHz", "44.1 kHz", "1.5 MHz"]', '44.1 kHz', '分类: Science: Computers', 20, 1, NOW(), NOW()),
  ('single', 'easy', 'How long is an IPv6 address?', '["32 bits", "128 bits", "128 bytes", "64 bits"]', '128 bits', '分类: Science: Computers', 10, 1, NOW(), NOW()),
  ('single', 'easy', 'What language does Node.js use?', '["JavaScript", "Java Source", "Java", "Joomla Source Code"]', 'JavaScript', '分类: Science: Computers', 10, 1, NOW(), NOW()),
  ('single', 'easy', 'Which computer hardware device provides an interface for all other connected devices to communicate?', '["Central Processing Unit", "Random Access Memory", "Motherboard", "Hard Disk Drive"]', 'Motherboard', '分类: Science: Computers', 10, 1, NOW(), NOW()),
  ('single', 'easy', 'What does LTS stand for in the software market?', '["Ludicrous Transfer Speed", "Ludicrous Turbo Speed", "Long Term Support", "Long Taco Service"]', 'Long Term Support', '分类: Science: Computers', 10, 1, NOW(), NOW()),
  ('single', 'hard', 'Which of the following is NOT a computer science algorithm?', '["Merge Sort", "Float Sort", "Bubble Sort", "Quick Sort"]', 'Float Sort', '分类: Science: Computers', 30, 1, NOW(), NOW()),
  ('single', 'easy', 'On Twitter, what was the original character limit for a Tweet?', '["120", "100", "160", "140"]', '140', '分类: Science: Computers', 10, 1, NOW(), NOW()),
  ('single', 'hard', 'Lenovo acquired IBM''s personal computer division, including the ThinkPad line of laptops and tablets, in what year?', '["2008", "2005", "2002", "1999"]', '2005', '分类: Science: Computers', 30, 1, NOW(), NOW()),
  ('single', 'medium', 'What was the name given to Android 4.3?', '["Froyo", "Lollipop", "Nutella", "Jelly Bean"]', 'Jelly Bean', '分类: Science: Computers', 20, 1, NOW(), NOW()),
  ('single', 'hard', 'Which of these was the name of a bug found in April 2014 in the publicly available OpenSSL cryptography library?', '["Shellscript", "Shellshock", "Heartbleed", "Corrupted Blood"]', 'Heartbleed', '分类: Science: Computers', 30, 1, NOW(), NOW()),
  ('single', 'hard', 'Which of these is not a key value of Agile software development?', '["Individuals and interactions", "Customer collaboration", "Comprehensive documentation", "Responding to change"]', 'Comprehensive documentation', '分类: Science: Computers', 30, 1, NOW(), NOW()),
  ('single', 'medium', 'Moore''s law originally stated that the number of transistors on a microprocessor chip would double every...', '["Eight Years", "Four Years", "Two Years", "Year"]', 'Year', '分类: Science: Computers', 20, 1, NOW(), NOW()),
  ('single', 'easy', 'Color model CMYK stands for?', '["Cyan, Magenta, Yellow, and Khaki", "Cream, Maroon, Yellow, and Black", "Cyan, Magenta, Yellow, and Black", "Cream, Maroon, Yellow, and Khaki"]', 'Cyan, Magenta, Yellow, and Black', '分类: Science: Computers', 10, 1, NOW(), NOW()),
  ('single', 'easy', 'On a standard American QWERTY keyboard, what symbol will you enter if you hold the shift key and press 1?', '["Percent Sign", "Dollar Sign", "Asterisk", "Exclamation Mark"]', 'Exclamation Mark', '分类: Science: Computers', 10, 1, NOW(), NOW()),
  ('single', 'easy', 'What does the computer software acronym JVM stand for?', '["Java Vendor Machine", "Java Visual Machine", "Just Virtual Machine", "Java Virtual Machine"]', 'Java Virtual Machine', '分类: Science: Computers', 10, 1, NOW(), NOW()),
  ('judge', 'easy', 'Time on Computers is measured via the EPOX System.', '["对", "错"]', '错', '分类: Science: Computers', 10, 1, NOW(), NOW()),
  ('single', 'hard', 'Which of the following physical typologies are used with Ethernet Networks?', '["Star", "Ring", "Hex", "Mesh"]', 'Star', '分类: Science: Computers', 30, 1, NOW(), NOW()),
  ('single', 'medium', 'What does AD stand for in relation to Windows Operating Systems? ', '["Alternative Drive", "Active Department", "Active Directory", "Automated Database"]', 'Active Directory', '分类: Science: Computers', 20, 1, NOW(), NOW()),
  ('single', 'easy', 'What is the commonly used keyboard shortcut for the ''Copy'' function on Windows OS?', '["Alt + C", "Alt + X", "Ctrl + C", "Ctrl + X"]', 'Ctrl + C', '分类: Science: Computers', 10, 1, NOW(), NOW()),
  ('judge', 'easy', 'The Windows 7 operating system has six main editions.', '["对", "错"]', '对', '分类: Science: Computers', 10, 1, NOW(), NOW());
