-- 中文题库数据
-- 共50道计算机科学题目

INSERT INTO questions (type, difficulty, content, options, answer, explanation, score, bank_id, create_time, update_time) VALUES
  ('single', 'medium', '在编程中，三元运算符通常用什么符号定义？', '["?", "?:", "if then", "??"]', '?:', '计算机科学基础', 20, 1, NOW(), NOW()),
  ('single', 'easy', 'Gmail首次推出时，提供多少存储空间？', '["无限", "1GB", "512MB", "5GB"]', '1GB', '计算机科学基础', 10, 1, NOW(), NOW()),
  ('judge', 'easy', '在大多数编程语言中，运算符 ++ 等同于语句 "+= 1"。', '["对", "错"]', '对', '计算机科学基础', 10, 1, NOW(), NOW()),
  ('judge', 'medium', 'Raspberry Pi 系列单板计算机是在美国创建的。', '["对", "错"]', '错', '计算机科学基础', 20, 1, NOW(), NOW()),
  ('single', 'medium', '世嘉Mega Drive / Sega Genesis的主CPU是什么？', '["Yamaha YM2612", "Zilog Z80", "Motorola 68000", "Intel 8088"]', 'Motorola 68000', '计算机科学基础', 20, 1, NOW(), NOW()),
  ('single', 'hard', 'FILO适用于哪种数据结构？', '["栈", "树", "队列", "堆"]', '栈', '数据结构', 30, 1, NOW(), NOW()),
  ('single', 'hard', 'Palantir的创始人是谁？', '["Peter Thiel", "Jack Dorsey", "Marc Benioff", "Mark Zuckerberg"]', 'Peter Thiel', '计算机科学基础', 30, 1, NOW(), NOW()),
  ('single', 'medium', '哪家互联网公司最初是一家名为''Cadabra''的网上书店？', '["Amazon", "Overstock", "Shopify", "eBay"]', 'Amazon', '计算机科学基础', 20, 1, NOW(), NOW()),
  ('judge', 'medium', 'AMD创造了第一款消费级64位处理器。', '["对", "错"]', '对', '计算机科学基础', 20, 1, NOW(), NOW()),
  ('single', 'easy', '在网络中，OSPF代表什么？', '["Open Signal Path Finder", "Open Shortest Path First", "Order State Part First", "Order Sense Ping Find"]', 'Open Shortest Path First', '网络基础', 10, 1, NOW(), NOW()),
  ('single', 'medium', '在HTML中，哪个非标准标签曾用于使元素在视口中滚动？', '["<marquee></marquee>", "<scroll></scroll>", "<slide></slide>", "<move></move>"]', '<marquee></marquee>', 'Web开发', 20, 1, NOW(), NOW()),
  ('judge', 'hard', 'DHCP代表动态主机配置端口(Dynamic Host Configuration Port)。', '["对", "错"]', '错', 'DHCP代表动态主机配置协议', 30, 1, NOW(), NOW()),
  ('single', 'medium', '以下哪个不是Ubuntu发行版的官方开发代号？', '["Wily Werewolf", "Utopic Unicorn", "Mystic Mansion", "Trusty Tahr"]', 'Mystic Mansion', '操作系统', 20, 1, NOW(), NOW()),
  ('single', 'medium', '在许多3D建模应用中常见的茶壶被称为什么？', '["3D茶壶", "皮克斯茶壶", "田纳西茶壶", "犹他茶壶"]', '犹他茶壶', '计算机图形学', 20, 1, NOW(), NOW()),
  ('single', 'hard', 'CMOS是用于构建集成电路的技术。CMOS代表什么？', '["互补金属氧化物半导体", "计算机制造振荡静态", "互补磁性欧姆半导体", "计算机制造操作系统"]', '互补金属氧化物半导体', '硬件基础', 30, 1, NOW(), NOW()),
  ('single', 'medium', '哪种编程语言是Sun Microsystems在1995年开发的？', '["Solaris OS", "C++", "Java", "Python"]', 'Java', '编程语言', 20, 1, NOW(), NOW()),
  ('judge', 'easy', 'Linus Torvalds创建了Linux和Git。', '["对", "错"]', '对', '开源软件', 10, 1, NOW(), NOW()),
  ('judge', 'easy', '编程语言AWK的名称是开发者名字Aho、Weinberger和Kernighan的缩写。', '["对", "错"]', '对', '编程语言', 10, 1, NOW(), NOW()),
  ('single', 'medium', '以下哪项是日本富士通公司生产的个人电脑？', '["MSX", "Xmillennium", "PC-9801", "FM-7"]', 'FM-7', '计算机历史', 20, 1, NOW(), NOW()),
  ('single', 'easy', 'SSD代表什么？', '["解决方案源磁盘", "源解决方案驱动器", "固态磁盘", "固态硬盘"]', '固态硬盘', '硬件基础', 10, 1, NOW(), NOW()),
  ('judge', 'medium', '常见的软件编程缩写"I18N"来自术语"Interlocalization"。', '["对", "错"]', '错', 'I18N来自Internationalization', 20, 1, NOW(), NOW()),
  ('single', 'medium', 'Tor匿名网络的名称最初代表什么？', '["The Only Router", "The Ominous Router", "The Onion Router", "The Orange Router"]', 'The Onion Router', '网络安全', 20, 1, NOW(), NOW()),
  ('single', 'hard', '哪种RAID阵列类型与数据镜像相关联？', '["RAID 5", "RAID 0", "RAID 1", "RAID 10"]', 'RAID 1', '存储技术', 30, 1, NOW(), NOW()),
  ('single', 'medium', '第一个专门针对平板电脑优化的Android版本是什么？', '["Eclair", "Froyo", "Honeycomb", "Marshmellow"]', 'Honeycomb', '移动开发', 20, 1, NOW(), NOW()),
  ('judge', 'easy', '编程语言"Python"是基于"JavaScript"的修改版本。', '["对", "错"]', '错', '编程语言', 10, 1, NOW(), NOW()),
  ('single', 'easy', '通常多少位等于一个字节？', '["64", "8", "1", "2"]', '8', '计算机基础', 10, 1, NOW(), NOW()),
  ('single', 'medium', '单精度浮点数的尾数部分由多少位组成？', '["8", "15", "53", "23"]', '23', '计算机基础', 20, 1, NOW(), NOW()),
  ('single', 'hard', '2001年发布的苹果Mac OS X操作系统第一版（版本10.0）的动物代号是什么？', '["Puma", "Cheetah", "Tiger", "Leopard"]', 'Cheetah', '操作系统', 30, 1, NOW(), NOW()),
  ('judge', 'medium', '开源程序Redis是一个关系型数据库服务器。', '["对", "错"]', '错', 'Redis是键值存储数据库', 20, 1, NOW(), NOW()),
  ('single', 'hard', '使用两位经典信息发送一位量子信息的过程叫什么名字？', '["量子纠缠", "量子隐形传态", "超密编码", "量子编程"]', '量子隐形传态', '量子计算', 30, 1, NOW(), NOW()),
  ('single', 'medium', '最初用于PCM适配器的CD数字音频格式的标准采样频率是多少？', '["32.0 kHz", "20.5 kHz", "44.1 kHz", "1.5 MHz"]', '44.1 kHz', '多媒体技术', 20, 1, NOW(), NOW()),
  ('single', 'easy', 'IPv6地址有多长？', '["32位", "128位", "128字节", "64位"]', '128位', '网络基础', 10, 1, NOW(), NOW()),
  ('single', 'easy', 'Node.js使用什么语言？', '["JavaScript", "Java Source", "Java", "Joomla Source Code"]', 'JavaScript', 'Web开发', 10, 1, NOW(), NOW()),
  ('single', 'easy', '哪个计算机硬件设备为所有其他连接设备提供通信接口？', '["中央处理器", "随机存取存储器", "主板", "硬盘驱动器"]', '主板', '硬件基础', 10, 1, NOW(), NOW()),
  ('single', 'easy', '在软件市场中，LTS代表什么？', '["Ludicrous Transfer Speed", "Ludicrous Turbo Speed", "长期支持", "Long Taco Service"]', '长期支持', '软件开发', 10, 1, NOW(), NOW()),
  ('single', 'hard', '以下哪项不是计算机科学算法？', '["归并排序", "浮点排序", "冒泡排序", "快速排序"]', '浮点排序', '算法基础', 30, 1, NOW(), NOW()),
  ('single', 'easy', '在Twitter上，一条Tweet的原始字符限制是多少？', '["120", "100", "160", "140"]', '140', '互联网服务', 10, 1, NOW(), NOW()),
  ('single', 'hard', '联想在哪一年收购了IBM的个人电脑部门，包括ThinkPad系列笔记本电脑和平板电脑？', '["2008", "2005", "2002", "1999"]', '2005', '计算机历史', 30, 1, NOW(), NOW()),
  ('single', 'medium', 'Android 4.3的名称是什么？', '["Froyo", "Lollipop", "Nutella", "Jelly Bean"]', 'Jelly Bean', '移动开发', 20, 1, NOW(), NOW()),
  ('single', 'hard', '以下哪项是2014年4月在公开可用的OpenSSL加密库中发现的漏洞名称？', '["Shellscript", "Shellshock", "Heartbleed", "Corrupted Blood"]', 'Heartbleed', '网络安全', 30, 1, NOW(), NOW()),
  ('single', 'hard', '以下哪项不是敏捷软件开发的核心价值观？', '["个体和互动", "客户协作", "全面文档", "响应变化"]', '全面文档', '软件开发方法论', 30, 1, NOW(), NOW()),
  ('single', 'medium', '摩尔定律最初指出，微处理器芯片上的晶体管数量每...翻一番。', '["八年", "四年", "两年", "一年"]', '一年', '计算机科学基础', 20, 1, NOW(), NOW()),
  ('single', 'easy', '颜色模型CMYK代表什么？', '["青色、品红色、黄色和卡其色", "奶油色、栗色、黄色和黑色", "青色、品红色、黄色和黑色", "奶油色、栗色、黄色和卡其色"]', '青色、品红色、黄色和黑色', '图形设计', 10, 1, NOW(), NOW()),
  ('single', 'easy', '在标准美式QWERTY键盘上，按住Shift键并按1会输入什么符号？', '["百分号", "美元符号", "星号", "感叹号"]', '感叹号', '计算机基础', 10, 1, NOW(), NOW()),
  ('single', 'easy', '计算机软件缩写JVM代表什么？', '["Java Vendor Machine", "Java Visual Machine", "Just Virtual Machine", "Java虚拟机"]', 'Java虚拟机', 'Java技术', 10, 1, NOW(), NOW()),
  ('judge', 'easy', '计算机上的时间是通过EPOX系统测量的。', '["对", "错"]', '错', '计算机时间通过Unix时间戳测量', 10, 1, NOW(), NOW()),
  ('single', 'hard', '以太网网络使用以下哪种物理拓扑结构？', '["星型", "环型", "六边形", "网状"]', '星型', '网络基础', 30, 1, NOW(), NOW()),
  ('single', 'medium', '在Windows操作系统中，AD代表什么？', '["Alternative Drive", "Active Department", "Active Directory", "Automated Database"]', 'Active Directory', 'Windows系统', 20, 1, NOW(), NOW()),
  ('single', 'easy', '在Windows操作系统上，"复制"功能的常用键盘快捷键是什么？', '["Alt + C", "Alt + X", "Ctrl + C", "Ctrl + X"]', 'Ctrl + C', '操作系统', 10, 1, NOW(), NOW()),
  ('judge', 'easy', 'Windows 7操作系统有六个主要版本。', '["对", "错"]', '对', '操作系统', 10, 1, NOW(), NOW());